//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Localization.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Localization.Models.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daire No.
        /// </summary>
        public static string ApartmentID {
            get {
                return ResourceManager.GetString("ApartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödeme Talimatı.
        /// </summary>
        public static string AutomaticPaymentInstruction {
            get {
                return ResourceManager.GetString("AutomaticPaymentInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tar..
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Tutarı.
        /// </summary>
        public static string BillAmount {
            get {
                return ResourceManager.GetString("BillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura No.
        /// </summary>
        public static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Sahibi Adı Soyadı.
        /// </summary>
        public static string CardholderName {
            get {
                return ResourceManager.GetString("CardholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Sahibi Adı Soyadı.
        /// </summary>
        public static string CCName {
            get {
                return ResourceManager.GetString("CCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taahhüt Bitiş Tarihi.
        /// </summary>
        public static string CommitmentExpirationDate {
            get {
                return ResourceManager.GetString("CommitmentExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taahhüt Süresi.
        /// </summary>
        public static string CommitmentLength {
            get {
                return ResourceManager.GetString("CommitmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Telefonu.
        /// </summary>
        public static string ContactPhoneNo {
            get {
                return ResourceManager.GetString("ContactPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Güvenlik Kodu (CVV).
        /// </summary>
        public static string CreditSecureCode {
            get {
                return ResourceManager.GetString("CreditSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online İşlem Merkezi Şifre.
        /// </summary>
        public static string CustomerServicePassword {
            get {
                return ResourceManager.GetString("CustomerServicePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string DistrictID {
            get {
                return ResourceManager.GetString("DistrictID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina No/Apt No..
        /// </summary>
        public static string DoorID {
            get {
                return ResourceManager.GetString("DoorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Noise Margin.
        /// </summary>
        public static string DownloadNoiseMargin {
            get {
                return ResourceManager.GetString("DownloadNoiseMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Hızı.
        /// </summary>
        public static string DownloadSpeed {
            get {
                return ResourceManager.GetString("DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Ödeme Tarihi.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanılan.
        /// </summary>
        public static string EarnDiscount {
            get {
                return ResourceManager.GetString("EarnDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Kullanım Tarihi (AY).
        /// </summary>
        public static string ExpirationDateMonth {
            get {
                return ResourceManager.GetString("ExpirationDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Kullanım Tarihi (YIL).
        /// </summary>
        public static string ExpirationDateYear {
            get {
                return ResourceManager.GetString("ExpirationDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat No.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı Soyadı.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturalama Tarihi.
        /// </summary>
        public static string InvoicingPeriod {
            get {
                return ResourceManager.GetString("InvoicingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresi.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Kesim Tarihi.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Ödeme Tarihi.
        /// </summary>
        public static string LastPaymentDate {
            get {
                return ResourceManager.GetString("LastPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Tesis Adresi.
        /// </summary>
        public static string LineAddress {
            get {
                return ResourceManager.GetString("LineAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Durumu.
        /// </summary>
        public static string LineState {
            get {
                return ResourceManager.GetString("LineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybedilen.
        /// </summary>
        public static string LoseDiscount {
            get {
                return ResourceManager.GetString("LoseDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybedilen.
        /// </summary>
        public static string MissedCount {
            get {
                return ResourceManager.GetString("MissedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Erişim Kullanıcı Şifresi.
        /// </summary>
        public static string ModemPassword {
            get {
                return ResourceManager.GetString("ModemPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Erişim Kullanıcı Adı.
        /// </summary>
        public static string ModemUsername {
            get {
                return ResourceManager.GetString("ModemUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahalle.
        /// </summary>
        public static string NeighbourhoodID {
            get {
                return ResourceManager.GetString("NeighbourhoodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş Fatura.
        /// </summary>
        public static string PassedInvoice {
            get {
                return ResourceManager.GetString("PassedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tipi.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiziksel Bağlantı.
        /// </summary>
        public static string PhysicalState {
            get {
                return ResourceManager.GetString("PhysicalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string ProvinceID {
            get {
                return ResourceManager.GetString("ProvinceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans No.
        /// </summary>
        public static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan.
        /// </summary>
        public static string RemainingCount {
            get {
                return ResourceManager.GetString("RemainingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan.
        /// </summary>
        public static string RemainingDiscount {
            get {
                return ResourceManager.GetString("RemainingDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        public static string RuralCode {
            get {
                return ResourceManager.GetString("RuralCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife.
        /// </summary>
        public static string ServiceID {
            get {
                return ResourceManager.GetString("ServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife Adı.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Referans Kodu.
        /// </summary>
        public static string SpecialOfferReferenceCode {
            get {
                return ResourceManager.GetString("SpecialOfferReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statik IP.
        /// </summary>
        public static string StaticIP {
            get {
                return ResourceManager.GetString("StaticIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sokak/Cadde.
        /// </summary>
        public static string StreetID {
            get {
                return ResourceManager.GetString("StreetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone No.
        /// </summary>
        public static string SubscriberNo {
            get {
                return ResourceManager.GetString("SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone Durum.
        /// </summary>
        public static string SubscriberState {
            get {
                return ResourceManager.GetString("SubscriberState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Hizmet Durumu.
        /// </summary>
        public static string SubscriptionLineState {
            get {
                return ResourceManager.GetString("SubscriptionLineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string SupportDate {
            get {
                return ResourceManager.GetString("SupportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek No.
        /// </summary>
        public static string SupportNo {
            get {
                return ResourceManager.GetString("SupportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Talebi Açıklaması.
        /// </summary>
        public static string SupportRequestSubType {
            get {
                return ResourceManager.GetString("SupportRequestSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Talebi Türü.
        /// </summary>
        public static string SupportRequestType {
            get {
                return ResourceManager.GetString("SupportRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik No veya GSM No.
        /// </summary>
        public static string TckGsmLogin {
            get {
                return ResourceManager.GetString("TckGsmLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Dönem.
        /// </summary>
        public static string ThisPeriod {
            get {
                return ResourceManager.GetString("ThisPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Dönem.
        /// </summary>
        public static string ThisPeriodDiscount {
            get {
                return ResourceManager.GetString("ThisPeriodDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanılan.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string TotalDownload {
            get {
                return ResourceManager.GetString("TotalDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string TotalUpload {
            get {
                return ResourceManager.GetString("TotalUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Kullanım.
        /// </summary>
        public static string TotalUsage {
            get {
                return ResourceManager.GetString("TotalUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Noise Margin.
        /// </summary>
        public static string UploadNoiseMargin {
            get {
                return ResourceManager.GetString("UploadNoiseMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplod Hızı.
        /// </summary>
        public static string UploadSpeed {
            get {
                return ResourceManager.GetString("UploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanılan.
        /// </summary>
        public static string UsedCount {
            get {
                return ResourceManager.GetString("UsedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanılan.
        /// </summary>
        public static string UseDiscount {
            get {
                return ResourceManager.GetString("UseDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devre Numarası.
        /// </summary>
        public static string XDSLNo {
            get {
                return ResourceManager.GetString("XDSLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Tipi.
        /// </summary>
        public static string XDSLType {
            get {
                return ResourceManager.GetString("XDSLType", resourceCulture);
            }
        }
    }
}
