//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Localization.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Güvenliği Hakkında.
        /// </summary>
        public static string AboutCardSecurity {
            get {
                return ResourceManager.GetString("AboutCardSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklifi Kabul Et.
        /// </summary>
        public static string AcceptOffer {
            get {
                return ResourceManager.GetString("AcceptOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Bilgileri.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Tercihleri.
        /// </summary>
        public static string AccountPrefers {
            get {
                return ResourceManager.GetString("AccountPrefers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödemeyi Etkinleştir.
        /// </summary>
        public static string ActivateAutomaticPayment {
            get {
                return ResourceManager.GetString("ActivateAutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Ekleme.
        /// </summary>
        public static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kart Ekle.
        /// </summary>
        public static string AddNewCard {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ekle.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Temsilcisi.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Destek Kayıtlarım.
        /// </summary>
        public static string AllSupportRequests {
            get {
                return ResourceManager.GetString("AllSupportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Vergiler Dahil.
        /// </summary>
        public static string AllTaxesIncluded {
            get {
                return ResourceManager.GetString("AllTaxesIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memnuniyet duyacağınızı düşündüğümüz ve ihtiyaç duyduğunuz internet gereksinimlerinizi en iyi şekilde karşılayacağına inandığımız hizmetimizi size sunmaktan mutluluk duyacağız. Bizi tercih ettiğiniz için teşekkür ederiz..
        /// </summary>
        public static string ApplicationCompletedDescription {
            get {
                return ResourceManager.GetString("ApplicationCompletedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvur.
        /// </summary>
        public static string ApplicationRegister {
            get {
                return ResourceManager.GetString("ApplicationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvurunuz başarılı bir şekilde tamamlandı. Bu aşamada Hizmetlerimizden faydalanmaya başlamanız için öncelikle sözleşmeyi indirmeniz, yazıcıdan çıktıları aldıktan sonra sözleşmenin tüm sayfalarına imza atmanız ve tarafımıza iletmeniz gerekmektedir. Önlü-Arkalı kimlik fotokopinizi aşağıdaki alana sürükleyerek veya tıklayarak yüklemeniz gerekmektedir..
        /// </summary>
        public static string ApplicationRegisteredDescription {
            get {
                return ResourceManager.GetString("ApplicationRegisteredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödeme.
        /// </summary>
        public static string AutomaticPayment {
            get {
                return ResourceManager.GetString("AutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödeme Talimatı.
        /// </summary>
        public static string AutomaticPaymentInstruction {
            get {
                return ResourceManager.GetString("AutomaticPaymentInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödeme Talimatı - Kart Ekleme.
        /// </summary>
        public static string AutoPaymentAndAddCard {
            get {
                return ResourceManager.GetString("AutoPaymentAndAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik ödeme için kart ekleyebilir veya kayıtlı kartları silebilirsiniz.
        /// </summary>
        public static string AutoPaymentAndAddCardDescription {
            get {
                return ResourceManager.GetString("AutoPaymentAndAddCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödeme Talimatı - Kartı Sil.
        /// </summary>
        public static string AutoPaymentAndRemoveCard {
            get {
                return ResourceManager.GetString("AutoPaymentAndRemoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura ve Ödemeler.
        /// </summary>
        public static string BillsAndPayments {
            get {
                return ResourceManager.GetString("BillsAndPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik ödeme için kart ekleyebilir veya kayıtlı kartları silebilirsiniz.
        /// </summary>
        public static string CanAddCardOrDeleteCard {
            get {
                return ResourceManager.GetString("CanAddCardOrDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartınız ile hemen ödeme yapabilirsiniz..
        /// </summary>
        public static string CanPayWithCreditCardNow {
            get {
                return ResourceManager.GetString("CanPayWithCreditCardNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim bilgilerinizi güncelleyebilirsiniz.
        /// </summary>
        public static string CanUpdateContactInformation {
            get {
                return ResourceManager.GetString("CanUpdateContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Bilgileri.
        /// </summary>
        public static string CardInformation {
            get {
                return ResourceManager.GetString("CardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir ve Kaydet.
        /// </summary>
        public static string ChangeAndSave {
            get {
                return ResourceManager.GetString("ChangeAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçim Yapınız.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemenizi yapmak için daha önce kaydetmiş olduğunuz kartlardan seçim yapınız..
        /// </summary>
        public static string ChooseCardForPay {
            get {
                return ResourceManager.GetString("ChooseCardForPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay Seçin.
        /// </summary>
        public static string ChooseMonth {
            get {
                return ResourceManager.GetString("ChooseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapmak istediğiniz abone numarasını seçiniz.
        /// </summary>
        public static string ChooseSubscriberNo {
            get {
                return ResourceManager.GetString("ChooseSubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl Seçin.
        /// </summary>
        public static string ChooseYear {
            get {
                return ResourceManager.GetString("ChooseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Giriş İçin Tıklayın.
        /// </summary>
        public static string ClickQuickLogin {
            get {
                return ResourceManager.GetString("ClickQuickLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlandı.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Tercihi.
        /// </summary>
        public static string ContactPrefer {
            get {
                return ResourceManager.GetString("ContactPrefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Durumu.
        /// </summary>
        public static string CustomerLineDetails {
            get {
                return ResourceManager.GetString("CustomerLineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihli Fatura.
        /// </summary>
        public static string DatedInvoice {
            get {
                return ResourceManager.GetString("DatedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartı Sil.
        /// </summary>
        public static string DeleteCard {
            get {
                return ResourceManager.GetString("DeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed Online İşlemler&apos;de kredi kartı ile faturanızı anında ödeyebilir, Destek talebi oluşturabilir ve daha bir çok işlemi 7/24 hızlı ve güvenli bir şekilde
        ///gerçekleştirebilirsiniz..
        /// </summary>
        public static string DescriptionCustomerService {
            get {
                return ResourceManager.GetString("DescriptionCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim toplamı.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonelik ile ilgili evrak ve belgelerinize erişim sağlayabilir ve indirebilirsiniz..
        /// </summary>
        public static string DocumentsDescription {
            get {
                return ResourceManager.GetString("DocumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Bağlantınızı Yapıyoruz.
        /// </summary>
        public static string DoInternetConnection {
            get {
                return ResourceManager.GetString("DoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu aşamada saha ekiplerimiz internet bağlantınızı yapacak. Diğer bir operatörden geçiş yaptıysanız tarafınıza SMS ile gönderilecek Kullanıcı adı ve şifrenizi Modem arayüzüne giriş yaparak tanımlamanız gerekmektedir. Bu aşamada bir sorun yaşarsanız 0850 800 5 800 numaralı müşteri destek hattımızdan destek alabilirsiniz..
        /// </summary>
        public static string DoInternetConnectionDescription {
            get {
                return ResourceManager.GetString("DoInternetConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndir&amp;Görüntüle.
        /// </summary>
        public static string DownloadAndDisplay {
            get {
                return ResourceManager.GetString("DownloadAndDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Olarak İndir.
        /// </summary>
        public static string DownloadAsPdf {
            get {
                return ResourceManager.GetString("DownloadAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSL.
        /// </summary>
        public static string DSL {
            get {
                return ResourceManager.GetString("DSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paketi Uzat.
        /// </summary>
        public static string ExtendPacket {
            get {
                return ResourceManager.GetString("ExtendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIBER.
        /// </summary>
        public static string Fiber {
            get {
                return ResourceManager.GetString("Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Eklendi.
        /// </summary>
        public static string FileAdded {
            get {
                return ResourceManager.GetString("FileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dondurulmuş.
        /// </summary>
        public static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı Soyadı.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenmemiş Faturanız var!.
        /// </summary>
        public static string HaveUnpaidBills {
            get {
                return ResourceManager.GetString("HaveUnpaidBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı aboneliğinize ait {1} adet ödenmesi gereken faturanız var.
        /// </summary>
        public static string HaveUnpaidBillsInfo {
            get {
                return ResourceManager.GetString("HaveUnpaidBillsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı aboneliğinize ait {1} adet ödenmesi gereken faturanız var..
        /// </summary>
        public static string HaveUnpaidInvoiceInfo {
            get {
                return ResourceManager.GetString("HaveUnpaidInvoiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online İşlemler | Netspeed.
        /// </summary>
        public static string HeadTitle {
            get {
                return ResourceManager.GetString("HeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Nasıl Yardımcı Olabiliriz ?.
        /// </summary>
        public static string HelpSupportQuestion {
            get {
                return ResourceManager.GetString("HelpSupportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik fotokopinizi buraya sürükleyin veya gözatmak için tıklayın.
        /// </summary>
        public static string IDCardDropDescription {
            get {
                return ResourceManager.GetString("IDCardDropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimliğinizin ön ve arka fotokopisini yüklemeniz gerekiyor.
        /// </summary>
        public static string IDCardRequiredPhotoDescription {
            get {
                return ResourceManager.GetString("IDCardRequiredPhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİ &amp; HİZMETLER.
        /// </summary>
        public static string InfoServices {
            get {
                return ResourceManager.GetString("InfoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemde.
        /// </summary>
        public static string InProcess {
            get {
                return ResourceManager.GetString("InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz jeton!.
        /// </summary>
        public static string InvalidTokenKey {
            get {
                return ResourceManager.GetString("InvalidTokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura ve Ödemeler.
        /// </summary>
        public static string InvoicePayments {
            get {
                return ResourceManager.GetString("InvoicePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturalarınızı görüntüleyebilir indirebilir ve ödeyebilirsiniz..
        /// </summary>
        public static string InvoicePaymentsDescription {
            get {
                return ResourceManager.GetString("InvoicePaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Dönemi.
        /// </summary>
        public static string InvoicePeriod {
            get {
                return ResourceManager.GetString("InvoicePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura ödemeleriniz daha önce kaydetmiş olduğunuz bu kart ile gerçekleşecektir..
        /// </summary>
        public static string InvoiceWillPayWithThisCard {
            get {
                return ResourceManager.GetString("InvoiceWillPayWithThisCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Giriş.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Bildirimler.
        /// </summary>
        public static string LastNotifications {
            get {
                return ResourceManager.GetString("LastNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota Kullanım (Limitsiz).
        /// </summary>
        public static string LimitlessQuota {
            get {
                return ResourceManager.GetString("LimitlessQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattınızın teknik ve durum bilgilerini görebilirsiniz..
        /// </summary>
        public static string LineDetailsDescription {
            get {
                return ResourceManager.GetString("LineDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Teknik Bilgiler.
        /// </summary>
        public static string LineDetailsHeader {
            get {
                return ResourceManager.GetString("LineDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Durumu.
        /// </summary>
        public static string LineState {
            get {
                return ResourceManager.GetString("LineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Teknik Durumu.
        /// </summary>
        public static string LineTechnicalState {
            get {
                return ResourceManager.GetString("LineTechnicalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 4 kayıt listelenmektedir...
        /// </summary>
        public static string ListLastFourRequest {
            get {
                return ResourceManager.GetString("ListLastFourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapılıyor.
        /// </summary>
        public static string LoggingOn {
            get {
                return ResourceManager.GetString("LoggingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM No veya TCK No.
        /// </summary>
        public static string LoginCustomerCode {
            get {
                return ResourceManager.GetString("LoginCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yaparak hizmetlerinizi inceleyebilir ve
        ///        faturalarınızı ödeyebilirsiniz..
        /// </summary>
        public static string LoginDescription {
            get {
                return ResourceManager.GetString("LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen SMS Şifre.
        /// </summary>
        public static string LoginSMSPassword {
            get {
                return ResourceManager.GetString("LoginSMSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik No veya GSM No.
        /// </summary>
        public static string LoginUsernamePlaceholder {
            get {
                return ResourceManager.GetString("LoginUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Şifre İle Giriş Yap.
        /// </summary>
        public static string LoginWithRegisteredPasssword {
            get {
                return ResourceManager.GetString("LoginWithRegisteredPasssword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string MailPlaceholder {
            get {
                return ResourceManager.GetString("MailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yaparak hizmetlerinizi inceleyebilir ve faturalarınızı ödeyebilirsiniz..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed Online İşlem Merkezi.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Kullanım.
        /// </summary>
        public static string MonthlyUse {
            get {
                return ResourceManager.GetString("MonthlyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Bilgilerim.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Ödemedeki Kredi Kartım.
        /// </summary>
        public static string MyCardInAutoPayment {
            get {
                return ResourceManager.GetString("MyCardInAutoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oim Hesabım.
        /// </summary>
        public static string MyCustomerServiceAccount {
            get {
                return ResourceManager.GetString("MyCustomerServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgelerim.
        /// </summary>
        public static string MyDocuments {
            get {
                return ResourceManager.GetString("MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturalarım.
        /// </summary>
        public static string MyInvoices {
            get {
                return ResourceManager.GetString("MyInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Kredi Kartlarım.
        /// </summary>
        public static string MyRegisteredCreditCards {
            get {
                return ResourceManager.GetString("MyRegisteredCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerim.
        /// </summary>
        public static string MyServices {
            get {
                return ResourceManager.GetString("MyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Taleplerim.
        /// </summary>
        public static string MySupportRequests {
            get {
                return ResourceManager.GetString("MySupportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifem.
        /// </summary>
        public static string MyTariff {
            get {
                return ResourceManager.GetString("MyTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Başvuru.
        /// </summary>
        public static string NewRegister {
            get {
                return ResourceManager.GetString("NewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Destek Kaydı.
        /// </summary>
        public static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek talebinde bulunabilir ve takip edebilirsiniz..
        /// </summary>
        public static string NewRequestDescription {
            get {
                return ResourceManager.GetString("NewRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Abonelik Başvurusu.
        /// </summary>
        public static string NewSubscriptionRegister {
            get {
                return ResourceManager.GetString("NewSubscriptionRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapınızı sorulayabilir ve yeni abonelik başvurusu yapabilirsiniz..
        /// </summary>
        public static string NewSubscriptionRegisterDescription {
            get {
                return ResourceManager.GetString("NewSubscriptionRegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni destek bildiriminiz var.
        /// </summary>
        public static string NewSupportNotification {
            get {
                return ResourceManager.GetString("NewSupportNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenmemiş Faturanız bulunmamaktadır.
        /// </summary>
        public static string NoHaveUnpaidBills {
            get {
                return ResourceManager.GetString("NoHaveUnpaidBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Uzunluğu {0} karakter olmalıdır. Şifre sadece harf ve sayılardan oluşmalıdır..
        /// </summary>
        public static string OnlinePasswordLengthDescription {
            get {
                return ResourceManager.GetString("OnlinePasswordLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Fatura Ödeme.
        /// </summary>
        public static string OnlinePayBill {
            get {
                return ResourceManager.GetString("OnlinePayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebi Tekrar Aç.
        /// </summary>
        public static string OpenRequestAgain {
            get {
                return ResourceManager.GetString("OpenRequestAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsteğe bağlı.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Sayfa gösteriliyor / Toplam {1} Sayfa.
        /// </summary>
        public static string PageSummary {
            get {
                return ResourceManager.GetString("PageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam {0} kayıt bulundu. Bu sayfada {1} ile {2} arası kayıtlar gösteriliyor..
        /// </summary>
        public static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödendi.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif.
        /// </summary>
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Öde.
        /// </summary>
        public static string PayAll {
            get {
                return ResourceManager.GetString("PayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Tutar.
        /// </summary>
        public static string PayingAmount {
            get {
                return ResourceManager.GetString("PayingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Ödeme.
        /// </summary>
        public static string PayingBills {
            get {
                return ResourceManager.GetString("PayingBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Bilgileri.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenliğiniz sebebi ile ödeme işleminiz &lt;strong&gt;3D secure&lt;/strong&gt; ile gerçekleşecektir..
        /// </summary>
        public static string PaymentSecureDescription {
            get {
                return ResourceManager.GetString("PaymentSecureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder butonuna bastıktan sonra sistemimiz sizi 3D güvenli ödeme alanına yönlendirecektir. Telefonunuza gelecek olan SMS de yer alan güvenlik şifresini girerek faturanızın ödemesini yapabilirsiniz..
        /// </summary>
        public static string PaymentSecureText {
            get {
                return ResourceManager.GetString("PaymentSecureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartları alınamadı. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        public static string PaymentWithCardNotAvailable {
            get {
                return ResourceManager.GetString("PaymentWithCardNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemeniz daha önce kaydetmiş olduğunuz bu kart ile gerçekleşecektir..
        /// </summary>
        public static string PayRegisteredCardDescription {
            get {
                return ResourceManager.GetString("PayRegisteredCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka/Kredi Kartı ile Ödeme.
        /// </summary>
        public static string PayWithBankCreditCard {
            get {
                return ResourceManager.GetString("PayWithBankCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Kart İle Ödeme.
        /// </summary>
        public static string PayWithRegisteredCard {
            get {
                return ResourceManager.GetString("PayWithRegisteredCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Ediliyor... Lütfen Bekleyin...
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme başarılı..
        /// </summary>
        public static string POSSuccessMessage {
            get {
                return ResourceManager.GetString("POSSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorunum Çözüldü.
        /// </summary>
        public static string ProblemSolved {
            get {
                return ResourceManager.GetString("ProblemSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı İşlemler.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Giriş Yap.
        /// </summary>
        public static string QuickLogin {
            get {
                return ResourceManager.GetString("QuickLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemen Öde.
        /// </summary>
        public static string QuickPay {
            get {
                return ResourceManager.GetString("QuickPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kota Paketleri.
        /// </summary>
        public static string QuotaPackages {
            get {
                return ResourceManager.GetString("QuotaPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife bilgilerinizi ve aylık kullanım durumunu görebilirsiniz.
        /// </summary>
        public static string RecipeUsageDescription {
            get {
                return ResourceManager.GetString("RecipeUsageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife ve Kullanım Bilgileriniz.
        /// </summary>
        public static string RecipeUsageInfo {
            get {
                return ResourceManager.GetString("RecipeUsageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönlendiriliyor... Lütfen Bekleyiniz...
        /// </summary>
        public static string Redirecting {
            get {
                return ResourceManager.GetString("Redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davet Kodu.
        /// </summary>
        public static string ReferenceCode {
            get {
                return ResourceManager.GetString("ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum Yenile.
        /// </summary>
        public static string RefreshState {
            get {
                return ResourceManager.GetString("RefreshState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Kartlar.
        /// </summary>
        public static string RegisteredCards {
            get {
                return ResourceManager.GetString("RegisteredCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik ödeme için kart ekleyebilir veya kayıtlı kartları silebilirsiniz.
        /// </summary>
        public static string RegisteredCardsDescription {
            get {
                return ResourceManager.GetString("RegisteredCardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuru Takibi.
        /// </summary>
        public static string RegisterTracking {
            get {
                return ResourceManager.GetString("RegisterTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Kota.
        /// </summary>
        public static string RemainingQuota {
            get {
                return ResourceManager.GetString("RemainingQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvurunuzu Aldık.
        /// </summary>
        public static string SavedYourApplication {
            get {
                return ResourceManager.GetString("SavedYourApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasıl yardımcı olabiliriz?.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenli Kart Ekleme.
        /// </summary>
        public static string SecureAddCard {
            get {
                return ResourceManager.GetString("SecureAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartı veri ve işlem güvenliğiniz dünyanın en üst düzey standardı olan PCI DSS LEVEL 1 uyumluluk sertifikasına sahip Mobilexpress altyapısı ile korunmaktadır..
        /// </summary>
        public static string SecureAddCardDescription1 {
            get {
                return ResourceManager.GetString("SecureAddCardDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Visa, Mastercard ve American Express logolu kredi kartları ve banka kartları (debit card) kaydedilebilir. İnternet kullanımına açık ve yeterli limiti bulunan tüm yurtiçi kredi kartları kullanılabilir..
        /// </summary>
        public static string SecureAddCardDescription2 {
            get {
                return ResourceManager.GetString("SecureAddCardDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemeleriniz için güvenli ödeme sayfası.
        /// </summary>
        public static string SecurePaymentPage {
            get {
                return ResourceManager.GetString("SecurePaymentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Faturaları Gör.
        /// </summary>
        public static string SeeAllInvoices {
            get {
                return ResourceManager.GetString("SeeAllInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Gönder.
        /// </summary>
        public static string SendPdfToMail {
            get {
                return ResourceManager.GetString("SendPdfToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kartınızın Son Kullanma Ayını girin..
        /// </summary>
        public static string SetCardExpirationMonth {
            get {
                return ResourceManager.GetString("SetCardExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kartınızın Son Kullanma Yılını girin..
        /// </summary>
        public static string SetCardExpirationYear {
            get {
                return ResourceManager.GetString("SetCardExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kart üzerinde yazan Ad ve Soyad giriniz.
        /// </summary>
        public static string SetCardFullName {
            get {
                return ResourceManager.GetString("SetCardFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Bilgilerini Giriniz.
        /// </summary>
        public static string SetCardInfoes {
            get {
                return ResourceManager.GetString("SetCardInfoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kart numarasını yazınız.
        /// </summary>
        public static string SetCardNumber {
            get {
                return ResourceManager.GetString("SetCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Haneli Güvenlik Kodunu girin..
        /// </summary>
        public static string SetCardSecureCode {
            get {
                return ResourceManager.GetString("SetCardSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Giriş Kodunu Giriniz.
        /// </summary>
        public static string SetLoginSMSCode {
            get {
                return ResourceManager.GetString("SetLoginSMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı GSM numarasına gönderdiğimiz Doğrulama Kodu&apos;nu giriniz.
        /// </summary>
        public static string SetValidationCode {
            get {
                return ResourceManager.GetString("SetValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Kodu.
        /// </summary>
        public static string SMSCode {
            get {
                return ResourceManager.GetString("SMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Doğrulaması.
        /// </summary>
        public static string SMSValidation {
            get {
                return ResourceManager.GetString("SMSValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Doğrulama Kodu.
        /// </summary>
        public static string SMSValidationCode {
            get {
                return ResourceManager.GetString("SMSValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya.
        /// </summary>
        public static string SpecialOffer {
            get {
                return ResourceManager.GetString("SpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya katılım şartları ve örnek paylaşım görselleri.
        /// </summary>
        public static string SpecialOfferConditionsSubtitle {
            get {
                return ResourceManager.GetString("SpecialOfferConditionsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed 12 Aylık İndirim Kodu.
        /// </summary>
        public static string SpecialOfferDiscountCodeHeader {
            get {
                return ResourceManager.GetString("SpecialOfferDiscountCodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir.
        /// </summary>
        public static string SpecialOfferFriends {
            get {
                return ResourceManager.GetString("SpecialOfferFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 ay boyunca daha az fatura öde!.
        /// </summary>
        public static string SpecialOfferIntro {
            get {
                return ResourceManager.GetString("SpecialOfferIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Özeti.
        /// </summary>
        public static string SpecialOfferSummary {
            get {
                return ResourceManager.GetString("SpecialOfferSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivasyon Sürecini Başlattık.
        /// </summary>
        public static string StartedActivation {
            get {
                return ResourceManager.GetString("StartedActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvurunuz sistemlerimize kayıt ediliyor hemen ardından internet bağlantınızın sağlanması için süreç başlayacak..
        /// </summary>
        public static string StartedActivationDescription {
            get {
                return ResourceManager.GetString("StartedActivationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM | BİLGİ.
        /// </summary>
        public static string StateInfo {
            get {
                return ResourceManager.GetString("StateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone Numarası.
        /// </summary>
        public static string SubscriberNo {
            get {
                return ResourceManager.GetString("SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone bulunamadı!.
        /// </summary>
        public static string SubscriberNotFound {
            get {
                return ResourceManager.GetString("SubscriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone Form &amp; Sözleşme.
        /// </summary>
        public static string SubscriptionFormAndContract {
            get {
                return ResourceManager.GetString("SubscriptionFormAndContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek &amp; Talepler.
        /// </summary>
        public static string SupportAndRequests {
            get {
                return ResourceManager.GetString("SupportAndRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Kayıtları.
        /// </summary>
        public static string SupportRecords {
            get {
                return ResourceManager.GetString("SupportRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Talebi.
        /// </summary>
        public static string SupportRequest {
            get {
                return ResourceManager.GetString("SupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Talebi Açıklaması.
        /// </summary>
        public static string SupportRequestExplain {
            get {
                return ResourceManager.GetString("SupportRequestExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek talebinizi lütfen kısa ve anlaşılır şekilde açıklayınız..
        /// </summary>
        public static string SupportRequestExplainText {
            get {
                return ResourceManager.GetString("SupportRequestExplainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Talepleri.
        /// </summary>
        public static string SupportRequests {
            get {
                return ResourceManager.GetString("SupportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek &amp; Talepler - Yeni Destek Kaydı.
        /// </summary>
        public static string SupportRequestsAndNewRequest {
            get {
                return ResourceManager.GetString("SupportRequestsAndNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Konusu.
        /// </summary>
        public static string SupportTopic {
            get {
                return ResourceManager.GetString("SupportTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife  Tercihi.
        /// </summary>
        public static string TariffPreference {
            get {
                return ResourceManager.GetString("TariffPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresinizde desteklenen altyapıya göre aşağıdaki tarifelerden seçim yapabilirsiniz..
        /// </summary>
        public static string TariffPreferenceDescription {
            get {
                return ResourceManager.GetString("TariffPreferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife &amp; Kullanım.
        /// </summary>
        public static string TariffUsage {
            get {
                return ResourceManager.GetString("TariffUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkürler.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyaları Yükle.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SON 3 DÖNEME AİT TRAFİK KULLANIM BİLGİSİ.
        /// </summary>
        public static string UsageInfoHeader {
            get {
                return ResourceManager.GetString("UsageInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğrulama ve Kaydetme.
        /// </summary>
        public static string ValidationAndSave {
            get {
                return ResourceManager.GetString("ValidationAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğrulama Kodu.
        /// </summary>
        public static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekliyor.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgelerinizi Bekliyoruz.
        /// </summary>
        public static string WaitingYourDocuments {
            get {
                return ResourceManager.GetString("WaitingYourDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evde kurulum hizmeti aldıysanız bu aşamada bir şey yapmanız gerekmiyor. Ekiplerimiz evraklarınızı sizden teslim alacaklar.&lt;br&gt;
        ///                                    Kurulum hizmeti almadıysanız belgelerinizi anlaşmalı olduğumuz MNG Kargo 289 192 075 gönderi kodu ile ücretsiz olarak gönderebilirsiniz. Belgelerinizi farklı bir kargo firması ile ücretini ödeyerek göndermek isterseniz Adresimiz : Netspeed İnternet A.Ş Saraylar Mah. 464. Sokak No:1 Durmuş Ali Çoban İş Merkezi Kat:3 No:9 20010 Merkezefendi/Denizli.
        /// </summary>
        public static string WaitingYourDocumentsDescription {
            get {
                return ResourceManager.GetString("WaitingYourDocumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size özel tarife teklifimiz var!.
        /// </summary>
        public static string WeHaveSpecialOffer {
            get {
                return ResourceManager.GetString("WeHaveSpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online İşlemler&apos;e Hoşgeldiniz.
        /// </summary>
        public static string WelcomeCustomerService {
            get {
                return ResourceManager.GetString("WelcomeCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kayıtlı Şifre İle.
        /// </summary>
        public static string WithCompanyRegisteredPassword {
            get {
                return ResourceManager.GetString("WithCompanyRegisteredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek kullanımlık şifre ile.
        /// </summary>
        public static string WithPassword {
            get {
                return ResourceManager.GetString("WithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Yazın.
        /// </summary>
        public static string WriteNote {
            get {
                return ResourceManager.GetString("WriteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuru Durumunuz.
        /// </summary>
        public static string YourApplicationState {
            get {
                return ResourceManager.GetString("YourApplicationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifeniz.
        /// </summary>
        public static string YourRecipe {
            get {
                return ResourceManager.GetString("YourRecipe", resourceCulture);
            }
        }
    }
}
