//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecialOffer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecialOffer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Localization.SpecialOffer", typeof(SpecialOffer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Kampanyası, davet kodunuz ile referans olarak Netspeed’e kazandırdığınız her bir yeni abonelik için 12 aylık fatura dönemi boyunca hem sizin hem de arkadaşınızın her faturasında 5&apos;er TL indirim hakkı kazanmanızı sağlayan bir kampanyadır..
        /// </summary>
        public static string HowJoinExplain1 {
            get {
                return ResourceManager.GetString("HowJoinExplain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size özel referans kodunuz ile davet etmiş olduğunuz arkadaşınız davet kodunu abonelik başlatırken başvuru esnasında 444 0 217 Numaralı Başvuru Hattı üzerinden satış temsilcimize beyan etmesi veya web sitemiz üzerinde yer alan abone başvuru formunu doldururken “referans kodu” alanına sizin verdiğiniz kodu yazması yeterlidir..
        /// </summary>
        public static string HowJoinExplain2 {
            get {
                return ResourceManager.GetString("HowJoinExplain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Kampanya Nedir ve Nasıl Katılabilirsiniz?.
        /// </summary>
        public static string HowJoinSpecialOffer {
            get {
                return ResourceManager.GetString("HowJoinSpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davet Kodunuz.
        /// </summary>
        public static string InviteCode {
            get {
                return ResourceManager.GetString("InviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Davet Et!.
        /// </summary>
        public static string InviteYourFriends {
            get {
                return ResourceManager.GetString("InviteYourFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ve gelecek dönemler için yapılacak olan indirimler referans kodunuz ile davet etmiş olduğunuz abonenin ve sizin bir önceki dönem faturalarınızın zamanında ödenip ödenmediğine ve davet edilen abonenin hattının aktif, dondurulmamış veya iptal edilmemiş olması şartlarına göre belirlenmektedir. &lt;br&gt; Faturası zamanında veya hiç ödenmemiş, Abonelik durumu; Dondurulmuş veya iptal edilmiş olan abonelikler için indirim hakkı kaybedilmektedir. Davetiniz ile Netspeed&apos;e katılan arkadaşlarınızın ilk çıkan faturaların [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SpecialOfferAbout {
            get {
                return ResourceManager.GetString("SpecialOfferAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Kampanya Şartları.
        /// </summary>
        public static string SpecialOfferConditions {
            get {
                return ResourceManager.GetString("SpecialOfferConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya kapsamında kazandığınız indirimleri takip edebilirsiniz..
        /// </summary>
        public static string SpecialOfferDescription {
            get {
                return ResourceManager.GetString("SpecialOfferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Detayları.
        /// </summary>
        public static string SpecialOfferDetails {
            get {
                return ResourceManager.GetString("SpecialOfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Referans Kampanyası.
        /// </summary>
        public static string SpecialOfferHeader {
            get {
                return ResourceManager.GetString("SpecialOfferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 ay boyunca daha az veya hiç fatura ödeme!.
        /// </summary>
        public static string SpecialOfferInfo1 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed’e arkadaşlarını davet et.
        /// </summary>
        public static string SpecialOfferInfo2 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktif hizmet almaya başlayan her abonelik için.
        /// </summary>
        public static string SpecialOfferInfo3 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 adet fatura dönemi boyunca indirim hakkı kazan..
        /// </summary>
        public static string SpecialOfferInfo4 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha fazla arkadaş getir daha az veya hiç fatura ödeme!..
        /// </summary>
        public static string SpecialOfferInfo5 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını getir kampanyası kapsamında kazandığınız toplam indirimleri ve bu dönem için faturanızdan düşülecek indirimlerin toplamını görebilirsiniz..
        /// </summary>
        public static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam(Adet İndirim).
        /// </summary>
        public static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
    }
}
