//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecialOffer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecialOffer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Localization.SpecialOffer", typeof(SpecialOffer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to be paid.
        /// </summary>
        public static string AmountToBePaid {
            get {
                return ResourceManager.GetString("AmountToBePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69 TL.
        /// </summary>
        public static string AmountToBePaidTotal {
            get {
                return ResourceManager.GetString("AmountToBePaidTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocak 2021.
        /// </summary>
        public static string BillingPeriodExample {
            get {
                return ResourceManager.GetString("BillingPeriodExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Kampanyası, davet kodunuz ile referans olarak Netspeed’e kazandırdığınız her bir yeni abonelik için 12 aylık fatura dönemi boyunca hem sizin hem de arkadaşınızın her faturasında 5&apos;er TL indirim hakkı kazanmanızı sağlayan bir kampanyadır..
        /// </summary>
        public static string HowJoinExplain1 {
            get {
                return ResourceManager.GetString("HowJoinExplain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size özel referans kodunuz ile davet etmiş olduğunuz arkadaşınız davet kodunu abonelik başlatırken başvuru esnasında 444 0 217 Numaralı Başvuru Hattı üzerinden satış temsilcimize beyan etmesi veya web sitemiz üzerinde yer alan abone başvuru formunu doldururken “referans kodu” alanına sizin verdiğiniz kodu yazması yeterlidir..
        /// </summary>
        public static string HowJoinExplain2 {
            get {
                return ResourceManager.GetString("HowJoinExplain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Kampanya Nedir ve Nasıl Katılabilirsiniz?.
        /// </summary>
        public static string HowJoinSpecialOffer {
            get {
                return ResourceManager.GetString("HowJoinSpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davet Kodunuz.
        /// </summary>
        public static string InviteCode {
            get {
                return ResourceManager.GetString("InviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Davet Et!.
        /// </summary>
        public static string InviteYourFriends {
            get {
                return ResourceManager.GetString("InviteYourFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ve gelecek dönemler için yapılacak olan indirimler referans kodunuz ile davet etmiş olduğunuz abonenin ve sizin bir önceki dönem faturalarınızın zamanında ödenip ödenmediğine ve davet edilen abonenin hattının aktif, dondurulmamış veya iptal edilmemiş olması şartlarına göre belirlenmektedir. &lt;br&gt; Faturası zamanında veya hiç ödenmemiş, Abonelik durumu; Dondurulmuş veya iptal edilmiş olan abonelikler için indirim hakkı kaybedilmektedir. Davetiniz ile Netspeed&apos;e katılan arkadaşlarınızın ilk çıkan faturaların [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SpecialOfferAbout {
            get {
                return ResourceManager.GetString("SpecialOfferAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Kampanya Şartları.
        /// </summary>
        public static string SpecialOfferConditions {
            get {
                return ResourceManager.GetString("SpecialOfferConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya kapsamında kazandığınız indirimleri takip edebilirsiniz..
        /// </summary>
        public static string SpecialOfferDescription {
            get {
                return ResourceManager.GetString("SpecialOfferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Detayları.
        /// </summary>
        public static string SpecialOfferDetails {
            get {
                return ResourceManager.GetString("SpecialOfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed&apos;e aşağıdaki kod ile başvuranlar, 12 ay indirimli internet kullanma hakkı kazanıyor, Davet kodumu kullanırsan hem sen hem de ben 12 ay indirimli internet kullanma hakkı kazanacağız. Üstelik katılım sınırı yok, sende arkadaşlarını davet et! ne kadar çok arkadaş, o kadar çok indirimli kullanım hakkı!.
        /// </summary>
        public static string SpecialOfferDiscountCodeDescription {
            get {
                return ResourceManager.GetString("SpecialOfferDiscountCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 referans x 5 TL İndirim toplamı.
        /// </summary>
        public static string SpecialOfferDiscountExample {
            get {
                return ResourceManager.GetString("SpecialOfferDiscountExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 25 TL.
        /// </summary>
        public static string SpecialOfferDiscountTotalExample {
            get {
                return ResourceManager.GetString("SpecialOfferDiscountTotalExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Referans Kampanyası.
        /// </summary>
        public static string SpecialOfferHeader {
            get {
                return ResourceManager.GetString("SpecialOfferHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 ay boyunca daha az veya hiç fatura ödeme!.
        /// </summary>
        public static string SpecialOfferInfo1 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netspeed’e arkadaşlarını davet et.
        /// </summary>
        public static string SpecialOfferInfo2 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktif hizmet almaya başlayan her abonelik için.
        /// </summary>
        public static string SpecialOfferInfo3 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 adet fatura dönemi boyunca indirim hakkı kazan..
        /// </summary>
        public static string SpecialOfferInfo4 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha fazla arkadaş getir daha az veya hiç fatura ödeme!..
        /// </summary>
        public static string SpecialOfferInfo5 {
            get {
                return ResourceManager.GetString("SpecialOfferInfo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını getir kampanyası kapsamında kazandığınız toplam indirimleri ve bu dönem için faturanızdan düşülecek indirimlerin toplamını görebilirsiniz..
        /// </summary>
        public static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75 Mbps&apos;e Kadar Limitsiz.
        /// </summary>
        public static string TariffExample {
            get {
                return ResourceManager.GetString("TariffExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94 TL.
        /// </summary>
        public static string TariffPriceExample {
            get {
                return ResourceManager.GetString("TariffPriceExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Nedir?.
        /// </summary>
        public static string Terms1 {
            get {
                return ResourceManager.GetString("Terms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazandığınız İndirimleri Nasıl Takip Edebilirsiniz?.
        /// </summary>
        public static string Terms10 {
            get {
                return ResourceManager.GetString("Terms10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazandığınız indirimleri Online İşlemler üzerinden takip edebilirsiniz..
        /// </summary>
        public static string Terms10Answer {
            get {
                return ResourceManager.GetString("Terms10Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını Getir Kampanyası, referans kodunuz ile Netspeed’e davet ederek kazandırdığınız her bir yeni abonelik için 12 adet fatura döneminde her faturanızda 5 TL indirim hakkı kazanmanızı sağlayan bir indirim kampanyasıdır..
        /// </summary>
        public static string Terms1Answer {
            get {
                return ResourceManager.GetString("Terms1Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasıl Çalışır?.
        /// </summary>
        public static string Terms2 {
            get {
                return ResourceManager.GetString("Terms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online İşlem Merkezi üzerinden “arkadaşını getir” sekmesine tıklayarak görebileceğiniz size özel referans kodunuz ile arkadaşlarınızı davet edebilirsiniz. Önermiş olduğunuz arkadaşınız indirim kodunu abonelik başlatırken başvuru esnasında 444 0 217 Numaralı Başvuru Hattı üzerinden satış temsilcimize beyan etmesi veya web sitemiz üzerinde yer alan abone başvuru formunu doldururken “referans kodu” alanına sizin verdiğiniz kodu yazması yeterlidir. Başvurunun tamamlanması sonrasında referans olunan kişinin akti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Terms2Answer {
            get {
                return ResourceManager.GetString("Terms2Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Örnek İndirimli Fatura.
        /// </summary>
        public static string Terms3 {
            get {
                return ResourceManager.GetString("Terms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimler Katılabilir?.
        /// </summary>
        public static string Terms4 {
            get {
                return ResourceManager.GetString("Terms4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bireysel, aktif ve T.C uyruklu müşterilerimiz kampanyadan faydalanabilirler..
        /// </summary>
        public static string Terms4Answer {
            get {
                return ResourceManager.GetString("Terms4Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşlarınızı Nasıl Davet Edebilirsiniz?.
        /// </summary>
        public static string Terms5 {
            get {
                return ResourceManager.GetString("Terms5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online İşlem Merkezi üzerinden alabileceğiniz size özel referans kodunuzu arkadaşınızla paylaşarak kampanyaya katılabilirsiniz..
        /// </summary>
        public static string Terms5Answer {
            get {
                return ResourceManager.GetString("Terms5Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirimler Faturalarınıza Ne Zaman Yansıtılır?.
        /// </summary>
        public static string Terms6 {
            get {
                return ResourceManager.GetString("Terms6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanılan indirimler bir sonraki fatura döneminde yansıtılacaktır. İndirimin yansıtılacağı fatura dönemi içerisinde referans ile gelen abone ve referans kodu sahibinin aboneliğini herhangi bir nedenle iptal etmesi veya aboneliğin fesih edilmesi halinde her iki tarafında indirim hakkı kaybolur..
        /// </summary>
        public static string Terms6Answer {
            get {
                return ResourceManager.GetString("Terms6Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Kapsamında Davet Limiti Var mı?.
        /// </summary>
        public static string Terms7 {
            get {
                return ResourceManager.GetString("Terms7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davet sınırı bulunmamaktadır. Dilediğiniz kadar arkadaşınızı davet edebilirsiniz. Ancak aylık ödeyeceğiniz fatura tutarından daha fazla indirim kazanmanız durumunda indirimleriniz sonraki aylara ait ödeme çıkan faturalarda yansıtılmak üzere devir edilir..
        /// </summary>
        public static string Terms7Answer {
            get {
                return ResourceManager.GetString("Terms7Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Ödemeleri Gecikirse Ne Olur?.
        /// </summary>
        public static string Terms8 {
            get {
                return ResourceManager.GetString("Terms8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşını getir kampanyası ile kazanılan indirimler referans kodu ile gelen abone ve referans kodu sahibi abone faturalarının düzenli ve zamanında ödenmesi durumunda geçerli olacaktır. Ödemesi geciken ve ödenmeyen faturalar olması halinde bir sonraki dönemin faturalarına indirim yansıtılmayacaktır. Gecikmiş fatura borcu daha sonra ödense dahi ilgili döneme ait indirim hakkı tamamen kaybedilir ve sonraki aylara yansıtılmaz..
        /// </summary>
        public static string Terms8Answer {
            get {
                return ResourceManager.GetString("Terms8Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkadaşınız Aboneliği İptal Ederse Ne Olacak?.
        /// </summary>
        public static string Terms9 {
            get {
                return ResourceManager.GetString("Terms9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans kodunuz ile abone olan arkadaşınızın herhangi bir sebeple aboneliğini sonlandırması halinde abonelik iptalinin gerçekleştiği ay dâhil gelecek dönemlerde yansıtılmak üzere iptali sağlanan abonelikten kazanılan tüm indirimler silinecektir..
        /// </summary>
        public static string Terms9Answer {
            get {
                return ResourceManager.GetString("Terms9Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Şartları &amp; Sıkça Sorulan Sorular.
        /// </summary>
        public static string TermsAndFAQ {
            get {
                return ResourceManager.GetString("TermsAndFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam(Adet İndirim).
        /// </summary>
        public static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
    }
}
